/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package stuGradeCalc;

import javax.swing.JOptionPane;

/**
 *
 * @author JAMIE.M1
 */
public class calculatorUI extends javax.swing.JFrame {

    /**
     * Creates new form calculatorUI
     */
    public calculatorUI() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        LStdntNum = new javax.swing.JLabel();
        LStdntName = new javax.swing.JLabel();
        etStdntNum = new javax.swing.JTextField();
        etStdntName = new javax.swing.JTextField();
        LSubjects = new javax.swing.JLabel();
        LEnglish = new javax.swing.JLabel();
        LAfrikaans = new javax.swing.JLabel();
        LMaths = new javax.swing.JLabel();
        EngRes = new javax.swing.JTextField();
        LResults = new javax.swing.JLabel();
        MathRes = new javax.swing.JTextField();
        AfrRes = new javax.swing.JTextField();
        LTotMrks = new javax.swing.JLabel();
        LPerc = new javax.swing.JLabel();
        LGrade = new javax.swing.JLabel();
        etTotMrks = new javax.swing.JTextField();
        etPerc = new javax.swing.JTextField();
        etGrade = new javax.swing.JTextField();
        btnCalc = new javax.swing.JButton();
        LPhys = new javax.swing.JLabel();
        PhysRes = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        Value = new javax.swing.JButton();

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel8.setText("Student Number:");

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel10.setText("Student Number:");

        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel1.setText("Student Grade Calculator");

        LStdntNum.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        LStdntNum.setText("Student Number:");

        LStdntName.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        LStdntName.setText("Name:");

        LSubjects.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        LSubjects.setText("Subjects:");

        LEnglish.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        LEnglish.setText("English:");

        LAfrikaans.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        LAfrikaans.setText("Afrikaans:");

        LMaths.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        LMaths.setText("Mathematics:");

        EngRes.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N

        LResults.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        LResults.setText("Results:");

        MathRes.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N

        AfrRes.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        AfrRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AfrResActionPerformed(evt);
            }
        });

        LTotMrks.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        LTotMrks.setText("Total Marks:");

        LPerc.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        LPerc.setText("Average:");

        LGrade.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        LGrade.setText("Grade:");

        etTotMrks.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        etTotMrks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etTotMrksActionPerformed(evt);
            }
        });

        etPerc.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        etPerc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etPercActionPerformed(evt);
            }
        });

        etGrade.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        etGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etGradeActionPerformed(evt);
            }
        });

        btnCalc.setBackground(new java.awt.Color(102, 255, 102));
        btnCalc.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btnCalc.setText("Calculate");
        btnCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcActionPerformed(evt);
            }
        });

        LPhys.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        LPhys.setText("Physical Sciences:");

        PhysRes.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N

        btnReset.setBackground(new java.awt.Color(102, 255, 102));
        btnReset.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        Value.setBackground(new java.awt.Color(255, 153, 153));
        Value.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        Value.setText("Enter a Value");
        Value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LStdntNum)
                            .addComponent(LStdntName)
                            .addComponent(LSubjects)
                            .addComponent(LEnglish)
                            .addComponent(LAfrikaans)
                            .addComponent(LMaths)
                            .addComponent(LTotMrks)
                            .addComponent(LPerc)
                            .addComponent(LGrade)
                            .addComponent(LPhys))
                        .addGap(113, 113, 113)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EngRes, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LResults)
                            .addComponent(MathRes, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AfrRes, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etTotMrks, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etPerc, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PhysRes, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(etGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(etStdntName, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(etStdntNum, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Value, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCalc, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(296, 296, 296))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Value, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LStdntNum)
                    .addComponent(etStdntNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LStdntName)
                    .addComponent(etStdntName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LSubjects)
                    .addComponent(LResults))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LEnglish)
                    .addComponent(EngRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LAfrikaans)
                    .addComponent(AfrRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LMaths)
                    .addComponent(MathRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LPhys)
                    .addComponent(PhysRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCalc)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LTotMrks)
                    .addComponent(etTotMrks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LPerc)
                    .addComponent(etPerc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LGrade)
                    .addComponent(etGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void AfrResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AfrResActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AfrResActionPerformed

    private void etTotMrksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etTotMrksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etTotMrksActionPerformed

    private void etPercActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etPercActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etPercActionPerformed

    private void etGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etGradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etGradeActionPerformed

    private void btnCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcActionPerformed
        // TODO add your handling code here:
        //calculate button code
        //the try catch sttament handles an exception, it picks up an error or errors that may exist
        try {
            int stn = Integer.parseInt(etStdntNum.getText());
            String stuname = etStdntName.getText();
            
            double phy = Double.parseDouble(PhysRes.getText());
            double afrik = Double.parseDouble(AfrRes.getText());
            double maths = Double.parseDouble(MathRes.getText());
            double eng = Double.parseDouble(EngRes.getText());
            
            //calculates total marks
            double total = phy + afrik + maths + eng;
            etTotMrks.setText(" " + total);
            
            //calculates percentage
            double per = (total / 400) * 100;
            etPerc.setText(" " + per);
            
            String grade;
            
            //Grade calculation
            if (per >= 90){
                grade = "A";
            } else if (per >= 80){
                grade = "B";
            } else if (per >= 70){
                grade = "C";
            } else if (per >= 60){
                grade = "D";
            } else if (per >= 50){
                grade = "E";
            } else {
                grade = "Poor";
            }
            
            //Displays result in TextField
            etGrade.setText(" " + grade);
            
            etTotMrks.setText(" " + total);
            etPerc.setText(" " + per);
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter numeric values");
        }
    }//GEN-LAST:event_btnCalcActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        //CLEARS THE TEXTFIELDS
        
        PhysRes.setText(" ");
        AfrRes.setText(" ");
        MathRes.setText(" ");
        EngRes.setText(" ");
        
        etStdntNum.setText(" ");
        etStdntName.setText(" ");
        
        etGrade.setText(" ");
        etPerc.setText(" ");
        etTotMrks.setText(" ");
    }//GEN-LAST:event_btnResetActionPerformed

    private void ValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValueActionPerformed
        String value = JOptionPane.showInputDialog("Enter a value");
        JOptionPane.showMessageDialog(null, "Your value was: '" + value + "'.");
    }//GEN-LAST:event_ValueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculatorUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AfrRes;
    private javax.swing.JTextField EngRes;
    private javax.swing.JLabel LAfrikaans;
    private javax.swing.JLabel LEnglish;
    private javax.swing.JLabel LGrade;
    private javax.swing.JLabel LMaths;
    private javax.swing.JLabel LPerc;
    private javax.swing.JLabel LPhys;
    private javax.swing.JLabel LResults;
    private javax.swing.JLabel LStdntName;
    private javax.swing.JLabel LStdntNum;
    private javax.swing.JLabel LSubjects;
    private javax.swing.JLabel LTotMrks;
    private javax.swing.JTextField MathRes;
    private javax.swing.JTextField PhysRes;
    private javax.swing.JButton Value;
    private javax.swing.JButton btnCalc;
    private javax.swing.JButton btnReset;
    private javax.swing.JTextField etGrade;
    private javax.swing.JTextField etPerc;
    private javax.swing.JTextField etStdntName;
    private javax.swing.JTextField etStdntNum;
    private javax.swing.JTextField etTotMrks;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
